@include('layouts.header')

<div class="example-demo ivu-col ivu-col-span-24"><div class="example-case"><div data-v-11a02437=""><div data-v-11a02437="" class="layout"><div data-v-11a02437="" class="ivu-layout"><div data-v-11a02437="" class="ivu-layout-header"><ul data-v-11a02437="" class="ivu-menu ivu-menu-dark ivu-menu-horizontal"><div data-v-11a02437="" class="layout-logo"></div> <div data-v-11a02437="" class="layout-nav"><li data-v-11a02437="" class="ivu-menu-item ivu-menu-item-active ivu-menu-item-selected"><i data-v-11a02437="" class="ivu-icon ivu-icon-ios-navigate"></i>
                                    Item 1
                                </li> <li data-v-11a02437="" class="ivu-menu-item"><i data-v-11a02437="" class="ivu-icon ivu-icon-ios-keypad"></i>
                                    Item 2
                                </li> <li data-v-11a02437="" class="ivu-menu-item"><i data-v-11a02437="" class="ivu-icon ivu-icon-ios-analytics"></i>
                                    Item 3
                                </li> <li data-v-11a02437="" class="ivu-menu-item"><i data-v-11a02437="" class="ivu-icon ivu-icon-ios-paper"></i>
                                    Item 4
                                </li></div></ul></div> <div data-v-11a02437="" class="ivu-layout" style="padding: 0px 50px;"><div data-v-11a02437="" class="ivu-breadcrumb" style="margin: 16px 0px;"><span data-v-11a02437=""><span class="ivu-breadcrumb-item-link">Home</span> <span class="ivu-breadcrumb-item-separator">/</span></span> <span data-v-11a02437=""><span class="ivu-breadcrumb-item-link">Components</span> <span class="ivu-breadcrumb-item-separator">/</span></span> <span data-v-11a02437=""><span class="ivu-breadcrumb-item-link">Layout</span> <span class="ivu-breadcrumb-item-separator">/</span></span></div> <div data-v-11a02437="" class="ivu-layout-content" style="padding: 24px 0px; min-height: 280px; background: rgb(255, 255, 255);"><div data-v-11a02437="" class="ivu-layout ivu-layout-has-sider"><div data-v-11a02437="" class="ivu-layout-sider" style="width: 200px; min-width: 200px; max-width: 200px; flex: 0 0 200px; background: white;"><span class="ivu-layout-sider-zero-width-trigger" style="display: none;"><i class="ivu-icon ivu-icon-navicon-round"></i></span> <div class="ivu-layout-sider-children"><ul data-v-11a02437="" class="ivu-menu ivu-menu-light ivu-menu-vertical" style="width: auto;"><li data-v-11a02437="" class="ivu-menu-submenu ivu-menu-item-active ivu-menu-opened ivu-menu-child-item-active"><div class="ivu-menu-submenu-title"><i data-v-11a02437="" class="ivu-icon ivu-icon-ios-navigate"></i>
                                                    Item 1
                                                    <i class="ivu-icon ivu-icon-ios-arrow-down ivu-menu-submenu-title-icon"></i></div> <ul class="ivu-menu" data-old-padding-top="" data-old-padding-bottom="" data-old-overflow="" style=""> <li data-v-11a02437="" class="ivu-menu-item" style="padding-left: 43px;">Option 1</li> <li data-v-11a02437="" class="ivu-menu-item ivu-menu-item-active ivu-menu-item-selected" style="padding-left: 43px;">Option 2</li> <li data-v-11a02437="" class="ivu-menu-item" style="padding-left: 43px;">Option 3</li></ul></li> <li data-v-11a02437="" class="ivu-menu-submenu"><div class="ivu-menu-submenu-title"><i data-v-11a02437="" class="ivu-icon ivu-icon-ios-keypad"></i>
                                                    Item 2
                                                    <i class="ivu-icon ivu-icon-ios-arrow-down ivu-menu-submenu-title-icon"></i></div> <ul class="ivu-menu" style="display: none;"> <li data-v-11a02437="" class="ivu-menu-item" style="padding-left: 43px;">Option 1</li> <li data-v-11a02437="" class="ivu-menu-item" style="padding-left: 43px;">Option 2</li></ul></li> <li data-v-11a02437="" class="ivu-menu-submenu"><div class="ivu-menu-submenu-title"><i data-v-11a02437="" class="ivu-icon ivu-icon-ios-analytics"></i>
                                                    Item 3
                                                    <i class="ivu-icon ivu-icon-ios-arrow-down ivu-menu-submenu-title-icon"></i></div> <ul class="ivu-menu" style="display: none;"> <li data-v-11a02437="" class="ivu-menu-item" style="padding-left: 43px;">Option 1</li> <li data-v-11a02437="" class="ivu-menu-item" style="padding-left: 43px;">Option 2</li></ul></li></ul></div> <div class="ivu-layout-sider-trigger" style="width: 200px; display: none;"><i class="ivu-icon ivu-icon-chevron-left ivu-layout-sider-trigger-icon"></i></div></div> <div data-v-11a02437="" class="ivu-layout-content" style="padding: 24px; min-height: 280px; background: rgb(255, 255, 255);">
                                    Content
                                </div></div></div></div> <div data-v-11a02437="" class="layout-footer-center ivu-layout-footer">2011-2016 © TalkingData</div></div></div></div></div> <header class="example-header"><span>



@include('layouts.footer')